// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: deposit/deposit/deposit.proto

package deposit

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositAmountItemsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DepositAmountItemsReq) Reset() {
	*x = DepositAmountItemsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsReq) ProtoMessage() {}

func (x *DepositAmountItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsReq.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsReq) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{0}
}

type DepositAmountItemsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*DepositAmountItemsRes_UAmountItemEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *DepositAmountItemsRes) Reset() {
	*x = DepositAmountItemsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes) ProtoMessage() {}

func (x *DepositAmountItemsRes) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1}
}

func (x *DepositAmountItemsRes) GetEntries() []*DepositAmountItemsRes_UAmountItemEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DepositAmountItemsRes_Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Id) Reset() {
	*x = DepositAmountItemsRes_Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Id) ProtoMessage() {}

func (x *DepositAmountItemsRes_Id) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Id.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Id) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DepositAmountItemsRes_Id) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DepositAmountItemsRes_Title struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Title) Reset() {
	*x = DepositAmountItemsRes_Title{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Title) ProtoMessage() {}

func (x *DepositAmountItemsRes_Title) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Title.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Title) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 1}
}

func (x *DepositAmountItemsRes_Title) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DepositAmountItemsRes_Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Status) Reset() {
	*x = DepositAmountItemsRes_Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Status) ProtoMessage() {}

func (x *DepositAmountItemsRes_Status) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Status.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Status) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 2}
}

func (x *DepositAmountItemsRes_Status) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DepositAmountItemsRes_Detail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Detail) Reset() {
	*x = DepositAmountItemsRes_Detail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Detail) ProtoMessage() {}

func (x *DepositAmountItemsRes_Detail) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Detail.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Detail) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 3}
}

func (x *DepositAmountItemsRes_Detail) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DepositAmountItemsRes_AmountCategoryId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_AmountCategoryId) Reset() {
	*x = DepositAmountItemsRes_AmountCategoryId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_AmountCategoryId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_AmountCategoryId) ProtoMessage() {}

func (x *DepositAmountItemsRes_AmountCategoryId) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_AmountCategoryId.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_AmountCategoryId) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 4}
}

func (x *DepositAmountItemsRes_AmountCategoryId) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DepositAmountItemsRes_Net struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Net) Reset() {
	*x = DepositAmountItemsRes_Net{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Net) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Net) ProtoMessage() {}

func (x *DepositAmountItemsRes_Net) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Net.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Net) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 5}
}

func (x *DepositAmountItemsRes_Net) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DepositAmountItemsRes_Min struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Min) Reset() {
	*x = DepositAmountItemsRes_Min{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Min) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Min) ProtoMessage() {}

func (x *DepositAmountItemsRes_Min) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Min.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Min) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 6}
}

func (x *DepositAmountItemsRes_Min) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DepositAmountItemsRes_Max struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Max) Reset() {
	*x = DepositAmountItemsRes_Max{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Max) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Max) ProtoMessage() {}

func (x *DepositAmountItemsRes_Max) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Max.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Max) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 7}
}

func (x *DepositAmountItemsRes_Max) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DepositAmountItemsRes_Fee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Fee) Reset() {
	*x = DepositAmountItemsRes_Fee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Fee) ProtoMessage() {}

func (x *DepositAmountItemsRes_Fee) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Fee.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Fee) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 8}
}

func (x *DepositAmountItemsRes_Fee) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DepositAmountItemsRes_Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Type) Reset() {
	*x = DepositAmountItemsRes_Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Type) ProtoMessage() {}

func (x *DepositAmountItemsRes_Type) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Type.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Type) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 9}
}

func (x *DepositAmountItemsRes_Type) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DepositAmountItemsRes_Logo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Logo) Reset() {
	*x = DepositAmountItemsRes_Logo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Logo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Logo) ProtoMessage() {}

func (x *DepositAmountItemsRes_Logo) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Logo.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Logo) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 10}
}

func (x *DepositAmountItemsRes_Logo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DepositAmountItemsRes_Sort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Sort) Reset() {
	*x = DepositAmountItemsRes_Sort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Sort) ProtoMessage() {}

func (x *DepositAmountItemsRes_Sort) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Sort.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Sort) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 11}
}

func (x *DepositAmountItemsRes_Sort) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DepositAmountItemsRes_Country struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Country) Reset() {
	*x = DepositAmountItemsRes_Country{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Country) ProtoMessage() {}

func (x *DepositAmountItemsRes_Country) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Country.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Country) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 12}
}

func (x *DepositAmountItemsRes_Country) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DepositAmountItemsRes_Currency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Currency) Reset() {
	*x = DepositAmountItemsRes_Currency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Currency) ProtoMessage() {}

func (x *DepositAmountItemsRes_Currency) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Currency.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Currency) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 13}
}

func (x *DepositAmountItemsRes_Currency) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DepositAmountItemsRes_Protocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Protocol) Reset() {
	*x = DepositAmountItemsRes_Protocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Protocol) ProtoMessage() {}

func (x *DepositAmountItemsRes_Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Protocol.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Protocol) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 14}
}

func (x *DepositAmountItemsRes_Protocol) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DepositAmountItemsRes_CreatedAt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_CreatedAt) Reset() {
	*x = DepositAmountItemsRes_CreatedAt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_CreatedAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_CreatedAt) ProtoMessage() {}

func (x *DepositAmountItemsRes_CreatedAt) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_CreatedAt.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_CreatedAt) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 15}
}

func (x *DepositAmountItemsRes_CreatedAt) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DepositAmountItemsRes_UpdatedAt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_UpdatedAt) Reset() {
	*x = DepositAmountItemsRes_UpdatedAt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_UpdatedAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_UpdatedAt) ProtoMessage() {}

func (x *DepositAmountItemsRes_UpdatedAt) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_UpdatedAt.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_UpdatedAt) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 16}
}

func (x *DepositAmountItemsRes_UpdatedAt) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DepositAmountItemsRes_Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DepositAmountItemsRes_Address) Reset() {
	*x = DepositAmountItemsRes_Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_Address) ProtoMessage() {}

func (x *DepositAmountItemsRes_Address) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_Address.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_Address) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 17}
}

func (x *DepositAmountItemsRes_Address) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DepositAmountItemsRes_UAmountItemEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               *DepositAmountItemsRes_Id               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            *DepositAmountItemsRes_Title            `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status           *DepositAmountItemsRes_Status           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Detail           *DepositAmountItemsRes_Detail           `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	AmountCategoryId *DepositAmountItemsRes_AmountCategoryId `protobuf:"bytes,5,opt,name=amount_category_id,json=amountCategoryId,proto3" json:"amount_category_id,omitempty"`
	Net              *DepositAmountItemsRes_Net              `protobuf:"bytes,6,opt,name=net,proto3" json:"net,omitempty"`
	Min              *DepositAmountItemsRes_Min              `protobuf:"bytes,7,opt,name=min,proto3" json:"min,omitempty"`
	Max              *DepositAmountItemsRes_Max              `protobuf:"bytes,8,opt,name=max,proto3" json:"max,omitempty"`
	Fee              *DepositAmountItemsRes_Fee              `protobuf:"bytes,9,opt,name=fee,proto3" json:"fee,omitempty"`
	Type             *DepositAmountItemsRes_Type             `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Logo             *DepositAmountItemsRes_Logo             `protobuf:"bytes,11,opt,name=logo,proto3" json:"logo,omitempty"`
	Sort             *DepositAmountItemsRes_Sort             `protobuf:"bytes,12,opt,name=sort,proto3" json:"sort,omitempty"`
	Country          *DepositAmountItemsRes_Country          `protobuf:"bytes,13,opt,name=country,proto3" json:"country,omitempty"`
	Currency         *DepositAmountItemsRes_Currency         `protobuf:"bytes,14,opt,name=currency,proto3" json:"currency,omitempty"`
	Protocol         *DepositAmountItemsRes_Protocol         `protobuf:"bytes,15,opt,name=protocol,proto3" json:"protocol,omitempty"`
	CreatedAt        *DepositAmountItemsRes_CreatedAt        `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *DepositAmountItemsRes_UpdatedAt        `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Address          *DepositAmountItemsRes_Address          `protobuf:"bytes,18,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *DepositAmountItemsRes_UAmountItemEntry) Reset() {
	*x = DepositAmountItemsRes_UAmountItemEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes_UAmountItemEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes_UAmountItemEntry) ProtoMessage() {}

func (x *DepositAmountItemsRes_UAmountItemEntry) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes_UAmountItemEntry.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes_UAmountItemEntry) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1, 18}
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetId() *DepositAmountItemsRes_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetTitle() *DepositAmountItemsRes_Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetStatus() *DepositAmountItemsRes_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetDetail() *DepositAmountItemsRes_Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetAmountCategoryId() *DepositAmountItemsRes_AmountCategoryId {
	if x != nil {
		return x.AmountCategoryId
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetNet() *DepositAmountItemsRes_Net {
	if x != nil {
		return x.Net
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetMin() *DepositAmountItemsRes_Min {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetMax() *DepositAmountItemsRes_Max {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetFee() *DepositAmountItemsRes_Fee {
	if x != nil {
		return x.Fee
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetType() *DepositAmountItemsRes_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetLogo() *DepositAmountItemsRes_Logo {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetSort() *DepositAmountItemsRes_Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetCountry() *DepositAmountItemsRes_Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetCurrency() *DepositAmountItemsRes_Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetProtocol() *DepositAmountItemsRes_Protocol {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetCreatedAt() *DepositAmountItemsRes_CreatedAt {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetUpdatedAt() *DepositAmountItemsRes_UpdatedAt {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DepositAmountItemsRes_UAmountItemEntry) GetAddress() *DepositAmountItemsRes_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_deposit_deposit_deposit_proto protoreflect.FileDescriptor

var file_deposit_deposit_deposit_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x22, 0xa5, 0x0e, 0x0a, 0x15, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x07, 0x65,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x64,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x55, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x1a, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x1a, 0x1d, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x1e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x1e, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x28, 0x0a, 0x10, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x4e,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x4d, 0x69, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x4d, 0x61, 0x78, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x46, 0x65, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a,
	0x1c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x1c, 0x0a,
	0x04, 0x4c, 0x6f, 0x67, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x1c, 0x0a, 0x04, 0x53,
	0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x1f, 0x0a, 0x07, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x20, 0x0a, 0x08, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x20, 0x0a, 0x08,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x21,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x21, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x1a, 0x1f, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x81, 0x09, 0x0a, 0x10, 0x55, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x31, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3a, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x64, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3d, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x5d, 0x0a, 0x12, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x52, 0x65, 0x73, 0x2e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x49, 0x64, 0x52, 0x10, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x52, 0x65, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x52, 0x03, 0x6e, 0x65, 0x74, 0x12, 0x34, 0x0a, 0x03,
	0x6d, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x4d, 0x69, 0x6e, 0x52, 0x03, 0x6d,
	0x69, 0x6e, 0x12, 0x34, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e,
	0x4d, 0x61, 0x78, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x34, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e,
	0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x65, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x37,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e,
	0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f,
	0x12, 0x37, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x53,
	0x6f, 0x72, 0x74, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x40, 0x0a, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x64, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x43, 0x0a, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x12, 0x43, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52,
	0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x47, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x47,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x11, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52,
	0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x40, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x66, 0x0a, 0x0a, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x53, 0x76, 0x63, 0x12, 0x58, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x12, 0x1e, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x1e, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65,
	0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_deposit_deposit_deposit_proto_rawDescOnce sync.Once
	file_deposit_deposit_deposit_proto_rawDescData = file_deposit_deposit_deposit_proto_rawDesc
)

func file_deposit_deposit_deposit_proto_rawDescGZIP() []byte {
	file_deposit_deposit_deposit_proto_rawDescOnce.Do(func() {
		file_deposit_deposit_deposit_proto_rawDescData = protoimpl.X.CompressGZIP(file_deposit_deposit_deposit_proto_rawDescData)
	})
	return file_deposit_deposit_deposit_proto_rawDescData
}

var file_deposit_deposit_deposit_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_deposit_deposit_deposit_proto_goTypes = []interface{}{
	(*DepositAmountItemsReq)(nil),                  // 0: deposit.DepositAmountItemsReq
	(*DepositAmountItemsRes)(nil),                  // 1: deposit.DepositAmountItemsRes
	(*DepositAmountItemsRes_Id)(nil),               // 2: deposit.DepositAmountItemsRes.Id
	(*DepositAmountItemsRes_Title)(nil),            // 3: deposit.DepositAmountItemsRes.Title
	(*DepositAmountItemsRes_Status)(nil),           // 4: deposit.DepositAmountItemsRes.Status
	(*DepositAmountItemsRes_Detail)(nil),           // 5: deposit.DepositAmountItemsRes.Detail
	(*DepositAmountItemsRes_AmountCategoryId)(nil), // 6: deposit.DepositAmountItemsRes.AmountCategoryId
	(*DepositAmountItemsRes_Net)(nil),              // 7: deposit.DepositAmountItemsRes.Net
	(*DepositAmountItemsRes_Min)(nil),              // 8: deposit.DepositAmountItemsRes.Min
	(*DepositAmountItemsRes_Max)(nil),              // 9: deposit.DepositAmountItemsRes.Max
	(*DepositAmountItemsRes_Fee)(nil),              // 10: deposit.DepositAmountItemsRes.Fee
	(*DepositAmountItemsRes_Type)(nil),             // 11: deposit.DepositAmountItemsRes.Type
	(*DepositAmountItemsRes_Logo)(nil),             // 12: deposit.DepositAmountItemsRes.Logo
	(*DepositAmountItemsRes_Sort)(nil),             // 13: deposit.DepositAmountItemsRes.Sort
	(*DepositAmountItemsRes_Country)(nil),          // 14: deposit.DepositAmountItemsRes.Country
	(*DepositAmountItemsRes_Currency)(nil),         // 15: deposit.DepositAmountItemsRes.Currency
	(*DepositAmountItemsRes_Protocol)(nil),         // 16: deposit.DepositAmountItemsRes.Protocol
	(*DepositAmountItemsRes_CreatedAt)(nil),        // 17: deposit.DepositAmountItemsRes.CreatedAt
	(*DepositAmountItemsRes_UpdatedAt)(nil),        // 18: deposit.DepositAmountItemsRes.UpdatedAt
	(*DepositAmountItemsRes_Address)(nil),          // 19: deposit.DepositAmountItemsRes.Address
	(*DepositAmountItemsRes_UAmountItemEntry)(nil), // 20: deposit.DepositAmountItemsRes.UAmountItemEntry
}
var file_deposit_deposit_deposit_proto_depIdxs = []int32{
	20, // 0: deposit.DepositAmountItemsRes.entries:type_name -> deposit.DepositAmountItemsRes.UAmountItemEntry
	2,  // 1: deposit.DepositAmountItemsRes.UAmountItemEntry.id:type_name -> deposit.DepositAmountItemsRes.Id
	3,  // 2: deposit.DepositAmountItemsRes.UAmountItemEntry.title:type_name -> deposit.DepositAmountItemsRes.Title
	4,  // 3: deposit.DepositAmountItemsRes.UAmountItemEntry.status:type_name -> deposit.DepositAmountItemsRes.Status
	5,  // 4: deposit.DepositAmountItemsRes.UAmountItemEntry.detail:type_name -> deposit.DepositAmountItemsRes.Detail
	6,  // 5: deposit.DepositAmountItemsRes.UAmountItemEntry.amount_category_id:type_name -> deposit.DepositAmountItemsRes.AmountCategoryId
	7,  // 6: deposit.DepositAmountItemsRes.UAmountItemEntry.net:type_name -> deposit.DepositAmountItemsRes.Net
	8,  // 7: deposit.DepositAmountItemsRes.UAmountItemEntry.min:type_name -> deposit.DepositAmountItemsRes.Min
	9,  // 8: deposit.DepositAmountItemsRes.UAmountItemEntry.max:type_name -> deposit.DepositAmountItemsRes.Max
	10, // 9: deposit.DepositAmountItemsRes.UAmountItemEntry.fee:type_name -> deposit.DepositAmountItemsRes.Fee
	11, // 10: deposit.DepositAmountItemsRes.UAmountItemEntry.type:type_name -> deposit.DepositAmountItemsRes.Type
	12, // 11: deposit.DepositAmountItemsRes.UAmountItemEntry.logo:type_name -> deposit.DepositAmountItemsRes.Logo
	13, // 12: deposit.DepositAmountItemsRes.UAmountItemEntry.sort:type_name -> deposit.DepositAmountItemsRes.Sort
	14, // 13: deposit.DepositAmountItemsRes.UAmountItemEntry.country:type_name -> deposit.DepositAmountItemsRes.Country
	15, // 14: deposit.DepositAmountItemsRes.UAmountItemEntry.currency:type_name -> deposit.DepositAmountItemsRes.Currency
	16, // 15: deposit.DepositAmountItemsRes.UAmountItemEntry.protocol:type_name -> deposit.DepositAmountItemsRes.Protocol
	17, // 16: deposit.DepositAmountItemsRes.UAmountItemEntry.created_at:type_name -> deposit.DepositAmountItemsRes.CreatedAt
	18, // 17: deposit.DepositAmountItemsRes.UAmountItemEntry.updated_at:type_name -> deposit.DepositAmountItemsRes.UpdatedAt
	19, // 18: deposit.DepositAmountItemsRes.UAmountItemEntry.address:type_name -> deposit.DepositAmountItemsRes.Address
	0,  // 19: deposit.DepositSvc.ListDepositAmountItems:input_type -> deposit.DepositAmountItemsReq
	1,  // 20: deposit.DepositSvc.ListDepositAmountItems:output_type -> deposit.DepositAmountItemsRes
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_deposit_deposit_deposit_proto_init() }
func file_deposit_deposit_deposit_proto_init() {
	if File_deposit_deposit_deposit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deposit_deposit_deposit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Title); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Detail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_AmountCategoryId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Net); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Min); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Max); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Fee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Logo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Sort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Country); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Currency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Protocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_CreatedAt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_UpdatedAt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes_UAmountItemEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deposit_deposit_deposit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deposit_deposit_deposit_proto_goTypes,
		DependencyIndexes: file_deposit_deposit_deposit_proto_depIdxs,
		MessageInfos:      file_deposit_deposit_deposit_proto_msgTypes,
	}.Build()
	File_deposit_deposit_deposit_proto = out.File
	file_deposit_deposit_deposit_proto_rawDesc = nil
	file_deposit_deposit_deposit_proto_goTypes = nil
	file_deposit_deposit_deposit_proto_depIdxs = nil
}
