// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: deposit/deposit/deposit.proto

package deposit

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositAmountItemsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DepositAmountItemsReq) Reset() {
	*x = DepositAmountItemsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsReq) ProtoMessage() {}

func (x *DepositAmountItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsReq.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsReq) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{0}
}

type UAmountItemEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title            string  `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Status           int64   `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Detail           string  `protobuf:"bytes,4,opt,name=Detail,proto3" json:"Detail,omitempty"`
	AmountCategoryId int64   `protobuf:"varint,5,opt,name=amount_category_id,json=amountCategoryId,proto3" json:"amount_category_id,omitempty"`
	Net              string  `protobuf:"bytes,6,opt,name=net,proto3" json:"net,omitempty"`
	Min              float64 `protobuf:"fixed64,7,opt,name=min,proto3" json:"min,omitempty"`
	Max              float64 `protobuf:"fixed64,8,opt,name=max,proto3" json:"max,omitempty"`
	Fee              float64 `protobuf:"fixed64,9,opt,name=fee,proto3" json:"fee,omitempty"`
	Type             int64   `protobuf:"varint,10,opt,name=type,proto3" json:"type,omitempty"`
	Logo             string  `protobuf:"bytes,11,opt,name=logo,proto3" json:"logo,omitempty"`
	Sort             int64   `protobuf:"varint,12,opt,name=sort,proto3" json:"sort,omitempty"`
	Country          string  `protobuf:"bytes,13,opt,name=country,proto3" json:"country,omitempty"`
	Currency         string  `protobuf:"bytes,14,opt,name=currency,proto3" json:"currency,omitempty"`
	Protocol         string  `protobuf:"bytes,15,opt,name=protocol,proto3" json:"protocol,omitempty"`
	CreatedAt        string  `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string  `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Address          string  `protobuf:"bytes,18,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *UAmountItemEntry) Reset() {
	*x = UAmountItemEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UAmountItemEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UAmountItemEntry) ProtoMessage() {}

func (x *UAmountItemEntry) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UAmountItemEntry.ProtoReflect.Descriptor instead.
func (*UAmountItemEntry) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{1}
}

func (x *UAmountItemEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UAmountItemEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UAmountItemEntry) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UAmountItemEntry) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *UAmountItemEntry) GetAmountCategoryId() int64 {
	if x != nil {
		return x.AmountCategoryId
	}
	return 0
}

func (x *UAmountItemEntry) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *UAmountItemEntry) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *UAmountItemEntry) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *UAmountItemEntry) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *UAmountItemEntry) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UAmountItemEntry) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *UAmountItemEntry) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UAmountItemEntry) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UAmountItemEntry) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UAmountItemEntry) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *UAmountItemEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UAmountItemEntry) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UAmountItemEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DepositAmountItemsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*UAmountItemEntry `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *DepositAmountItemsRes) Reset() {
	*x = DepositAmountItemsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_deposit_deposit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAmountItemsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAmountItemsRes) ProtoMessage() {}

func (x *DepositAmountItemsRes) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_deposit_deposit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAmountItemsRes.ProtoReflect.Descriptor instead.
func (*DepositAmountItemsRes) Descriptor() ([]byte, []int) {
	return file_deposit_deposit_deposit_proto_rawDescGZIP(), []int{2}
}

func (x *DepositAmountItemsRes) GetList() []*UAmountItemEntry {
	if x != nil {
		return x.List
	}
	return nil
}

var File_deposit_deposit_deposit_proto protoreflect.FileDescriptor

var file_deposit_deposit_deposit_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x22, 0xc4, 0x03, 0x0a, 0x10, 0x55, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x2c, 0x0a, 0x12,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78,
	0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x66,
	0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x46, 0x0a, 0x15, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65,
	0x73, 0x12, 0x2d, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x55, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x32, 0x66, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x53, 0x76, 0x63, 0x12, 0x58,
	0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1e, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x64, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_deposit_deposit_deposit_proto_rawDescOnce sync.Once
	file_deposit_deposit_deposit_proto_rawDescData = file_deposit_deposit_deposit_proto_rawDesc
)

func file_deposit_deposit_deposit_proto_rawDescGZIP() []byte {
	file_deposit_deposit_deposit_proto_rawDescOnce.Do(func() {
		file_deposit_deposit_deposit_proto_rawDescData = protoimpl.X.CompressGZIP(file_deposit_deposit_deposit_proto_rawDescData)
	})
	return file_deposit_deposit_deposit_proto_rawDescData
}

var file_deposit_deposit_deposit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_deposit_deposit_deposit_proto_goTypes = []interface{}{
	(*DepositAmountItemsReq)(nil), // 0: deposit.DepositAmountItemsReq
	(*UAmountItemEntry)(nil),      // 1: deposit.UAmountItemEntry
	(*DepositAmountItemsRes)(nil), // 2: deposit.DepositAmountItemsRes
}
var file_deposit_deposit_deposit_proto_depIdxs = []int32{
	1, // 0: deposit.DepositAmountItemsRes.list:type_name -> deposit.UAmountItemEntry
	0, // 1: deposit.DepositSvc.ListDepositAmountItems:input_type -> deposit.DepositAmountItemsReq
	2, // 2: deposit.DepositSvc.ListDepositAmountItems:output_type -> deposit.DepositAmountItemsRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_deposit_deposit_deposit_proto_init() }
func file_deposit_deposit_deposit_proto_init() {
	if File_deposit_deposit_deposit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deposit_deposit_deposit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UAmountItemEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_deposit_deposit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAmountItemsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deposit_deposit_deposit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deposit_deposit_deposit_proto_goTypes,
		DependencyIndexes: file_deposit_deposit_deposit_proto_depIdxs,
		MessageInfos:      file_deposit_deposit_deposit_proto_msgTypes,
	}.Build()
	File_deposit_deposit_deposit_proto = out.File
	file_deposit_deposit_deposit_proto_rawDesc = nil
	file_deposit_deposit_deposit_proto_goTypes = nil
	file_deposit_deposit_deposit_proto_depIdxs = nil
}
