// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: user/deposit/deposit.proto

package deposit

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DepositService_ListDepositAmountItems_FullMethodName = "/deposit.DepositService/ListDepositAmountItems"
	DepositService_CreateDeposit_FullMethodName          = "/deposit.DepositService/CreateDeposit"
)

// DepositServiceClient is the client API for DepositService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepositServiceClient interface {
	ListDepositAmountItems(ctx context.Context, in *DepositAmountItemsReq, opts ...grpc.CallOption) (*DepositAmountItemsRes, error)
	CreateDeposit(ctx context.Context, in *CreateDepositReq, opts ...grpc.CallOption) (*CreateDepositRes, error)
}

type depositServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepositServiceClient(cc grpc.ClientConnInterface) DepositServiceClient {
	return &depositServiceClient{cc}
}

func (c *depositServiceClient) ListDepositAmountItems(ctx context.Context, in *DepositAmountItemsReq, opts ...grpc.CallOption) (*DepositAmountItemsRes, error) {
	out := new(DepositAmountItemsRes)
	err := c.cc.Invoke(ctx, DepositService_ListDepositAmountItems_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositServiceClient) CreateDeposit(ctx context.Context, in *CreateDepositReq, opts ...grpc.CallOption) (*CreateDepositRes, error) {
	out := new(CreateDepositRes)
	err := c.cc.Invoke(ctx, DepositService_CreateDeposit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepositServiceServer is the server API for DepositService service.
// All implementations must embed UnimplementedDepositServiceServer
// for forward compatibility
type DepositServiceServer interface {
	ListDepositAmountItems(context.Context, *DepositAmountItemsReq) (*DepositAmountItemsRes, error)
	CreateDeposit(context.Context, *CreateDepositReq) (*CreateDepositRes, error)
	mustEmbedUnimplementedDepositServiceServer()
}

// UnimplementedDepositServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDepositServiceServer struct {
}

func (UnimplementedDepositServiceServer) ListDepositAmountItems(context.Context, *DepositAmountItemsReq) (*DepositAmountItemsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDepositAmountItems not implemented")
}
func (UnimplementedDepositServiceServer) CreateDeposit(context.Context, *CreateDepositReq) (*CreateDepositRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeposit not implemented")
}
func (UnimplementedDepositServiceServer) mustEmbedUnimplementedDepositServiceServer() {}

// UnsafeDepositServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepositServiceServer will
// result in compilation errors.
type UnsafeDepositServiceServer interface {
	mustEmbedUnimplementedDepositServiceServer()
}

func RegisterDepositServiceServer(s grpc.ServiceRegistrar, srv DepositServiceServer) {
	s.RegisterService(&DepositService_ServiceDesc, srv)
}

func _DepositService_ListDepositAmountItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositAmountItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositServiceServer).ListDepositAmountItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositService_ListDepositAmountItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositServiceServer).ListDepositAmountItems(ctx, req.(*DepositAmountItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositService_CreateDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDepositReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositServiceServer).CreateDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositService_CreateDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositServiceServer).CreateDeposit(ctx, req.(*CreateDepositReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DepositService_ServiceDesc is the grpc.ServiceDesc for DepositService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepositService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deposit.DepositService",
	HandlerType: (*DepositServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDepositAmountItems",
			Handler:    _DepositService_ListDepositAmountItems_Handler,
		},
		{
			MethodName: "CreateDeposit",
			Handler:    _DepositService_CreateDeposit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/deposit/deposit.proto",
}
