// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: book/english/english.proto

package english

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestEnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestEnReq) Reset() {
	*x = TestEnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_book_english_english_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestEnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestEnReq) ProtoMessage() {}

func (x *TestEnReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_english_english_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestEnReq.ProtoReflect.Descriptor instead.
func (*TestEnReq) Descriptor() ([]byte, []int) {
	return file_book_english_english_proto_rawDescGZIP(), []int{0}
}

type TestEnRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestEnRes) Reset() {
	*x = TestEnRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_book_english_english_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestEnRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestEnRes) ProtoMessage() {}

func (x *TestEnRes) ProtoReflect() protoreflect.Message {
	mi := &file_book_english_english_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestEnRes.ProtoReflect.Descriptor instead.
func (*TestEnRes) Descriptor() ([]byte, []int) {
	return file_book_english_english_proto_rawDescGZIP(), []int{1}
}

var File_book_english_english_proto protoreflect.FileDescriptor

var file_book_english_english_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x65, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x2f, 0x65,
	0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x6e,
	0x67, 0x6c, 0x69, 0x73, 0x68, 0x22, 0x0b, 0x0a, 0x09, 0x74, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x52,
	0x65, 0x71, 0x22, 0x0b, 0x0a, 0x09, 0x74, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x52, 0x65, 0x73, 0x32,
	0x46, 0x0a, 0x0e, 0x45, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x12,
	0x12, 0x2e, 0x65, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x45, 0x6e,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x65, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x45, 0x6e, 0x52, 0x65, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x65, 0x6e, 0x67,
	0x6c, 0x69, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_book_english_english_proto_rawDescOnce sync.Once
	file_book_english_english_proto_rawDescData = file_book_english_english_proto_rawDesc
)

func file_book_english_english_proto_rawDescGZIP() []byte {
	file_book_english_english_proto_rawDescOnce.Do(func() {
		file_book_english_english_proto_rawDescData = protoimpl.X.CompressGZIP(file_book_english_english_proto_rawDescData)
	})
	return file_book_english_english_proto_rawDescData
}

var file_book_english_english_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_book_english_english_proto_goTypes = []interface{}{
	(*TestEnReq)(nil), // 0: english.testEnReq
	(*TestEnRes)(nil), // 1: english.testEnRes
}
var file_book_english_english_proto_depIdxs = []int32{
	0, // 0: english.EnglishService.GetEnglish:input_type -> english.testEnReq
	1, // 1: english.EnglishService.GetEnglish:output_type -> english.testEnRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_book_english_english_proto_init() }
func file_book_english_english_proto_init() {
	if File_book_english_english_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_book_english_english_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestEnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_book_english_english_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestEnRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_book_english_english_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_english_english_proto_goTypes,
		DependencyIndexes: file_book_english_english_proto_depIdxs,
		MessageInfos:      file_book_english_english_proto_msgTypes,
	}.Build()
	File_book_english_english_proto = out.File
	file_book_english_english_proto_rawDesc = nil
	file_book_english_english_proto_goTypes = nil
	file_book_english_english_proto_depIdxs = nil
}
