// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: game/game/game.proto

package game

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BannerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BannerReq) Reset() {
	*x = BannerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_game_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerReq) ProtoMessage() {}

func (x *BannerReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerReq.ProtoReflect.Descriptor instead.
func (*BannerReq) Descriptor() ([]byte, []int) {
	return file_game_game_game_proto_rawDescGZIP(), []int{0}
}

type BannerItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Link  string `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *BannerItem) Reset() {
	*x = BannerItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_game_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerItem) ProtoMessage() {}

func (x *BannerItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerItem.ProtoReflect.Descriptor instead.
func (*BannerItem) Descriptor() ([]byte, []int) {
	return file_game_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *BannerItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BannerItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BannerItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BannerItem) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type BannerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*BannerItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *BannerRes) Reset() {
	*x = BannerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_game_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerRes) ProtoMessage() {}

func (x *BannerRes) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerRes.ProtoReflect.Descriptor instead.
func (*BannerRes) Descriptor() ([]byte, []int) {
	return file_game_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *BannerRes) GetList() []*BannerItem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_game_game_game_proto protoreflect.FileDescriptor

var file_game_game_game_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x0b, 0x0a, 0x09,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x5c, 0x0a, 0x0a, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x31, 0x0a, 0x09, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0x3d, 0x0a, 0x0b, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x42,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x67,
	0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_game_game_proto_rawDescOnce sync.Once
	file_game_game_game_proto_rawDescData = file_game_game_game_proto_rawDesc
)

func file_game_game_game_proto_rawDescGZIP() []byte {
	file_game_game_game_proto_rawDescOnce.Do(func() {
		file_game_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_game_game_proto_rawDescData)
	})
	return file_game_game_game_proto_rawDescData
}

var file_game_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_game_game_game_proto_goTypes = []interface{}{
	(*BannerReq)(nil),  // 0: game.BannerReq
	(*BannerItem)(nil), // 1: game.BannerItem
	(*BannerRes)(nil),  // 2: game.BannerRes
}
var file_game_game_game_proto_depIdxs = []int32{
	1, // 0: game.BannerRes.list:type_name -> game.BannerItem
	0, // 1: game.GameService.ListBanner:input_type -> game.BannerReq
	2, // 2: game.GameService.ListBanner:output_type -> game.BannerRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_game_game_proto_init() }
func file_game_game_game_proto_init() {
	if File_game_game_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_game_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_game_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_game_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_game_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_game_game_proto_goTypes,
		DependencyIndexes: file_game_game_game_proto_depIdxs,
		MessageInfos:      file_game_game_game_proto_msgTypes,
	}.Build()
	File_game_game_game_proto = out.File
	file_game_game_game_proto_rawDesc = nil
	file_game_game_game_proto_goTypes = nil
	file_game_game_game_proto_depIdxs = nil
}
