// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: user/mailbox/mailbox.proto

package mailbox

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserService_ListMailBox_FullMethodName             = "/mailbox.UserService/ListMailBox"
	UserService_CountMailBoxTotalUnRead_FullMethodName = "/mailbox.UserService/CountMailBoxTotalUnRead"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	ListMailBox(ctx context.Context, in *ListMailBoxReq, opts ...grpc.CallOption) (*ListMailBoxRes, error)
	CountMailBoxTotalUnRead(ctx context.Context, in *MailBoxTotalUnReadReq, opts ...grpc.CallOption) (*MailBoxTotalUnReadRes, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListMailBox(ctx context.Context, in *ListMailBoxReq, opts ...grpc.CallOption) (*ListMailBoxRes, error) {
	out := new(ListMailBoxRes)
	err := c.cc.Invoke(ctx, UserService_ListMailBox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CountMailBoxTotalUnRead(ctx context.Context, in *MailBoxTotalUnReadReq, opts ...grpc.CallOption) (*MailBoxTotalUnReadRes, error) {
	out := new(MailBoxTotalUnReadRes)
	err := c.cc.Invoke(ctx, UserService_CountMailBoxTotalUnRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	ListMailBox(context.Context, *ListMailBoxReq) (*ListMailBoxRes, error)
	CountMailBoxTotalUnRead(context.Context, *MailBoxTotalUnReadReq) (*MailBoxTotalUnReadRes, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) ListMailBox(context.Context, *ListMailBoxReq) (*ListMailBoxRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMailBox not implemented")
}
func (UnimplementedUserServiceServer) CountMailBoxTotalUnRead(context.Context, *MailBoxTotalUnReadReq) (*MailBoxTotalUnReadRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountMailBoxTotalUnRead not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_ListMailBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMailBoxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListMailBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListMailBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListMailBox(ctx, req.(*ListMailBoxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CountMailBoxTotalUnRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailBoxTotalUnReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CountMailBoxTotalUnRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CountMailBoxTotalUnRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CountMailBoxTotalUnRead(ctx, req.(*MailBoxTotalUnReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mailbox.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMailBox",
			Handler:    _UserService_ListMailBox_Handler,
		},
		{
			MethodName: "CountMailBoxTotalUnRead",
			Handler:    _UserService_CountMailBoxTotalUnRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/mailbox/mailbox.proto",
}
