// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: user/sys/sys.proto

package sys

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnnouncementReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AnnouncementReq) Reset() {
	*x = AnnouncementReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_sys_sys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnouncementReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementReq) ProtoMessage() {}

func (x *AnnouncementReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_sys_sys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementReq.ProtoReflect.Descriptor instead.
func (*AnnouncementReq) Descriptor() ([]byte, []int) {
	return file_user_sys_sys_proto_rawDescGZIP(), []int{0}
}

type AnnouncementRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Announcement string `protobuf:"bytes,1,opt,name=announcement,proto3" json:"announcement,omitempty"`
}

func (x *AnnouncementRes) Reset() {
	*x = AnnouncementRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_sys_sys_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnouncementRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementRes) ProtoMessage() {}

func (x *AnnouncementRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_sys_sys_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementRes.ProtoReflect.Descriptor instead.
func (*AnnouncementRes) Descriptor() ([]byte, []int) {
	return file_user_sys_sys_proto_rawDescGZIP(), []int{1}
}

func (x *AnnouncementRes) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

var File_user_sys_sys_proto protoreflect.FileDescriptor

var file_user_sys_sys_proto_rawDesc = []byte{
	0x0a, 0x12, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x79, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x79, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x6e, 0x6e,
	0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x22, 0x35, 0x0a, 0x0f,
	0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x32, 0x4b, 0x0a, 0x0a, 0x53, 0x79, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75,
	0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x73, 0x79, 0x73,
	0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x73, 0x79, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_user_sys_sys_proto_rawDescOnce sync.Once
	file_user_sys_sys_proto_rawDescData = file_user_sys_sys_proto_rawDesc
)

func file_user_sys_sys_proto_rawDescGZIP() []byte {
	file_user_sys_sys_proto_rawDescOnce.Do(func() {
		file_user_sys_sys_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_sys_sys_proto_rawDescData)
	})
	return file_user_sys_sys_proto_rawDescData
}

var file_user_sys_sys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_sys_sys_proto_goTypes = []interface{}{
	(*AnnouncementReq)(nil), // 0: sys.AnnouncementReq
	(*AnnouncementRes)(nil), // 1: sys.AnnouncementRes
}
var file_user_sys_sys_proto_depIdxs = []int32{
	0, // 0: sys.SysService.GetAnnouncement:input_type -> sys.AnnouncementReq
	1, // 1: sys.SysService.GetAnnouncement:output_type -> sys.AnnouncementRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_sys_sys_proto_init() }
func file_user_sys_sys_proto_init() {
	if File_user_sys_sys_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_sys_sys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnouncementReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_sys_sys_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnouncementRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_sys_sys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_sys_sys_proto_goTypes,
		DependencyIndexes: file_user_sys_sys_proto_depIdxs,
		MessageInfos:      file_user_sys_sys_proto_msgTypes,
	}.Build()
	File_user_sys_sys_proto = out.File
	file_user_sys_sys_proto_rawDesc = nil
	file_user_sys_sys_proto_goTypes = nil
	file_user_sys_sys_proto_depIdxs = nil
}
