// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: user/withdraw/withdraw.proto

package withdraw

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// pay password status
type PayPassStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *PayPassStatusReq) Reset() {
	*x = PayPassStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayPassStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayPassStatusReq) ProtoMessage() {}

func (x *PayPassStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayPassStatusReq.ProtoReflect.Descriptor instead.
func (*PayPassStatusReq) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{0}
}

func (x *PayPassStatusReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type PayPassStatusRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty" dc:"0 not set , 1 already set"` // 0 not set , 1 already set
}

func (x *PayPassStatusRes) Reset() {
	*x = PayPassStatusRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayPassStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayPassStatusRes) ProtoMessage() {}

func (x *PayPassStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayPassStatusRes.ProtoReflect.Descriptor instead.
func (*PayPassStatusRes) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{1}
}

func (x *PayPassStatusRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// set pay password
type SetPayPassReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Pass string `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (x *SetPayPassReq) Reset() {
	*x = SetPayPassReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPayPassReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPayPassReq) ProtoMessage() {}

func (x *SetPayPassReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPayPassReq.ProtoReflect.Descriptor instead.
func (*SetPayPassReq) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{2}
}

func (x *SetPayPassReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SetPayPassReq) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type SetPayPassRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetPayPassRes) Reset() {
	*x = SetPayPassRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPayPassRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPayPassRes) ProtoMessage() {}

func (x *SetPayPassRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPayPassRes.ProtoReflect.Descriptor instead.
func (*SetPayPassRes) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{3}
}

// bind withdraw account
type BindWithdrawAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BankId  int64  `protobuf:"varint,1,opt,name=bankId,proto3" json:"bankId,omitempty" dc:"bank id"`      // bank id
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty" dc:"card number"` // card number
	Title   string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty" dc:"cardholder"`      // cardholder
	Pass    string `protobuf:"bytes,4,opt,name=pass,proto3" json:"pass,omitempty" dc:"pay pass"`          // pay pass
	Uid     int64  `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *BindWithdrawAccountReq) Reset() {
	*x = BindWithdrawAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindWithdrawAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindWithdrawAccountReq) ProtoMessage() {}

func (x *BindWithdrawAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindWithdrawAccountReq.ProtoReflect.Descriptor instead.
func (*BindWithdrawAccountReq) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{4}
}

func (x *BindWithdrawAccountReq) GetBankId() int64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

func (x *BindWithdrawAccountReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BindWithdrawAccountReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BindWithdrawAccountReq) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

func (x *BindWithdrawAccountReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type BindWithdrawAccountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BindWithdrawAccountRes) Reset() {
	*x = BindWithdrawAccountRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindWithdrawAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindWithdrawAccountRes) ProtoMessage() {}

func (x *BindWithdrawAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindWithdrawAccountRes.ProtoReflect.Descriptor instead.
func (*BindWithdrawAccountRes) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{5}
}

// del withdraw account
type DelWithdrawAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id      int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PayPass string `protobuf:"bytes,3,opt,name=payPass,proto3" json:"payPass,omitempty"`
}

func (x *DelWithdrawAccountReq) Reset() {
	*x = DelWithdrawAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelWithdrawAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelWithdrawAccountReq) ProtoMessage() {}

func (x *DelWithdrawAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelWithdrawAccountReq.ProtoReflect.Descriptor instead.
func (*DelWithdrawAccountReq) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{6}
}

func (x *DelWithdrawAccountReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DelWithdrawAccountReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DelWithdrawAccountReq) GetPayPass() string {
	if x != nil {
		return x.PayPass
	}
	return ""
}

type DelWithdrawAccountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelWithdrawAccountRes) Reset() {
	*x = DelWithdrawAccountRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelWithdrawAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelWithdrawAccountRes) ProtoMessage() {}

func (x *DelWithdrawAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelWithdrawAccountRes.ProtoReflect.Descriptor instead.
func (*DelWithdrawAccountRes) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{7}
}

// list withdraw account
type ListWithdrawAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Uid  int64 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ListWithdrawAccountReq) Reset() {
	*x = ListWithdrawAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWithdrawAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWithdrawAccountReq) ProtoMessage() {}

func (x *ListWithdrawAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWithdrawAccountReq.ProtoReflect.Descriptor instead.
func (*ListWithdrawAccountReq) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{8}
}

func (x *ListWithdrawAccountReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWithdrawAccountReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListWithdrawAccountReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type WithdrawAccountItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Net      string `protobuf:"bytes,2,opt,name=net,proto3" json:"net,omitempty"`
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Address  string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status   string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Title    string `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *WithdrawAccountItem) Reset() {
	*x = WithdrawAccountItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawAccountItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawAccountItem) ProtoMessage() {}

func (x *WithdrawAccountItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawAccountItem.ProtoReflect.Descriptor instead.
func (*WithdrawAccountItem) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{9}
}

func (x *WithdrawAccountItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WithdrawAccountItem) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *WithdrawAccountItem) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *WithdrawAccountItem) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WithdrawAccountItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *WithdrawAccountItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WithdrawAccountItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ListWithdrawAccountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*WithdrawAccountItem `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListWithdrawAccountRes) Reset() {
	*x = ListWithdrawAccountRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWithdrawAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWithdrawAccountRes) ProtoMessage() {}

func (x *ListWithdrawAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWithdrawAccountRes.ProtoReflect.Descriptor instead.
func (*ListWithdrawAccountRes) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{10}
}

func (x *ListWithdrawAccountRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWithdrawAccountRes) GetList() []*WithdrawAccountItem {
	if x != nil {
		return x.List
	}
	return nil
}

// list withdrawal method
type ListWithdrawMethodReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Lang string `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
}

func (x *ListWithdrawMethodReq) Reset() {
	*x = ListWithdrawMethodReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWithdrawMethodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWithdrawMethodReq) ProtoMessage() {}

func (x *ListWithdrawMethodReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWithdrawMethodReq.ProtoReflect.Descriptor instead.
func (*ListWithdrawMethodReq) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{11}
}

func (x *ListWithdrawMethodReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListWithdrawMethodReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type WithdrawBindInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Protocol string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

func (x *WithdrawBindInfo) Reset() {
	*x = WithdrawBindInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawBindInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawBindInfo) ProtoMessage() {}

func (x *WithdrawBindInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawBindInfo.ProtoReflect.Descriptor instead.
func (*WithdrawBindInfo) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{12}
}

func (x *WithdrawBindInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WithdrawBindInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type AmountItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string            `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Detail       string            `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Logo         string            `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	Country      string            `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Currency     string            `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Protocol     string            `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Address      string            `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	ExchangeRate float64           `protobuf:"fixed64,9,opt,name=exchangeRate,proto3" json:"exchangeRate,omitempty"`
	SelectMoney  string            `protobuf:"bytes,10,opt,name=selectMoney,proto3" json:"selectMoney,omitempty"`
	Bind         *WithdrawBindInfo `protobuf:"bytes,11,opt,name=bind,proto3" json:"bind,omitempty" dc:"if it's empty go to bind"` // if it's empty go to bind
}

func (x *AmountItem) Reset() {
	*x = AmountItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AmountItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmountItem) ProtoMessage() {}

func (x *AmountItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmountItem.ProtoReflect.Descriptor instead.
func (*AmountItem) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{13}
}

func (x *AmountItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AmountItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AmountItem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AmountItem) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *AmountItem) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AmountItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AmountItem) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AmountItem) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AmountItem) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *AmountItem) GetSelectMoney() string {
	if x != nil {
		return x.SelectMoney
	}
	return ""
}

func (x *AmountItem) GetBind() *WithdrawBindInfo {
	if x != nil {
		return x.Bind
	}
	return nil
}

type ListWithdrawMethodRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tips string        `protobuf:"bytes,1,opt,name=tips,proto3" json:"tips,omitempty"`
	List []*AmountItem `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListWithdrawMethodRes) Reset() {
	*x = ListWithdrawMethodRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWithdrawMethodRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWithdrawMethodRes) ProtoMessage() {}

func (x *ListWithdrawMethodRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWithdrawMethodRes.ProtoReflect.Descriptor instead.
func (*ListWithdrawMethodRes) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{14}
}

func (x *ListWithdrawMethodRes) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

func (x *ListWithdrawMethodRes) GetList() []*AmountItem {
	if x != nil {
		return x.List
	}
	return nil
}

// create withdraw
type CreateWithdrawReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AmountItemId      int64   `protobuf:"varint,1,opt,name=amountItemId,proto3" json:"amountItemId,omitempty"`
	Amount            float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	WithdrawAccountId int64   `protobuf:"varint,3,opt,name=withdrawAccountId,proto3" json:"withdrawAccountId,omitempty"`
	Lang              string  `protobuf:"bytes,4,opt,name=lang,proto3" json:"lang,omitempty"`
	Uid               int64   `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *CreateWithdrawReq) Reset() {
	*x = CreateWithdrawReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithdrawReq) ProtoMessage() {}

func (x *CreateWithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithdrawReq.ProtoReflect.Descriptor instead.
func (*CreateWithdrawReq) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{15}
}

func (x *CreateWithdrawReq) GetAmountItemId() int64 {
	if x != nil {
		return x.AmountItemId
	}
	return 0
}

func (x *CreateWithdrawReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateWithdrawReq) GetWithdrawAccountId() int64 {
	if x != nil {
		return x.WithdrawAccountId
	}
	return 0
}

func (x *CreateWithdrawReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *CreateWithdrawReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CreateWithdrawRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateWithdrawRes) Reset() {
	*x = CreateWithdrawRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWithdrawRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithdrawRes) ProtoMessage() {}

func (x *CreateWithdrawRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithdrawRes.ProtoReflect.Descriptor instead.
func (*CreateWithdrawRes) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{16}
}

// list withdraw
type ListWithdrawReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ListWithdrawReq) Reset() {
	*x = ListWithdrawReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWithdrawReq) ProtoMessage() {}

func (x *ListWithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWithdrawReq.ProtoReflect.Descriptor instead.
func (*ListWithdrawReq) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{17}
}

func (x *ListWithdrawReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListWithdrawReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWithdrawReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type WithdrawItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo      string `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Uid          string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Status       string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty" dc:"1 wait 2 success -1 fail"` // 1 wait 2 success -1 fail
	FinishAt     string `protobuf:"bytes,4,opt,name=finishAt,proto3" json:"finishAt,omitempty"`
	Detail       string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	StatusRemark string `protobuf:"bytes,6,opt,name=statusRemark,proto3" json:"statusRemark,omitempty"`
	Amount       string `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	SysRemark    string `protobuf:"bytes,8,opt,name=sysRemark,proto3" json:"sysRemark,omitempty"`
	Address      string `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Fee          string `protobuf:"bytes,10,opt,name=fee,proto3" json:"fee,omitempty"`
	Net          string `protobuf:"bytes,11,opt,name=net,proto3" json:"net,omitempty"`
	Currency     string `protobuf:"bytes,12,opt,name=currency,proto3" json:"currency,omitempty"`
	Protocol     string `protobuf:"bytes,13,opt,name=protocol,proto3" json:"protocol,omitempty"`
	CreatedAt    string `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *WithdrawItem) Reset() {
	*x = WithdrawItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawItem) ProtoMessage() {}

func (x *WithdrawItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawItem.ProtoReflect.Descriptor instead.
func (*WithdrawItem) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{18}
}

func (x *WithdrawItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *WithdrawItem) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *WithdrawItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WithdrawItem) GetFinishAt() string {
	if x != nil {
		return x.FinishAt
	}
	return ""
}

func (x *WithdrawItem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *WithdrawItem) GetStatusRemark() string {
	if x != nil {
		return x.StatusRemark
	}
	return ""
}

func (x *WithdrawItem) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *WithdrawItem) GetSysRemark() string {
	if x != nil {
		return x.SysRemark
	}
	return ""
}

func (x *WithdrawItem) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WithdrawItem) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *WithdrawItem) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *WithdrawItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *WithdrawItem) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *WithdrawItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListWithdrawRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64           `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*WithdrawItem `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListWithdrawRes) Reset() {
	*x = ListWithdrawRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWithdrawRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWithdrawRes) ProtoMessage() {}

func (x *ListWithdrawRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWithdrawRes.ProtoReflect.Descriptor instead.
func (*ListWithdrawRes) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{19}
}

func (x *ListWithdrawRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWithdrawRes) GetList() []*WithdrawItem {
	if x != nil {
		return x.List
	}
	return nil
}

// list public withdraw
type ListPublicWithdrawReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPublicWithdrawReq) Reset() {
	*x = ListPublicWithdrawReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPublicWithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicWithdrawReq) ProtoMessage() {}

func (x *ListPublicWithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicWithdrawReq.ProtoReflect.Descriptor instead.
func (*ListPublicWithdrawReq) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{20}
}

type PublicWithdrawItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo      string `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Uid          string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Status       string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty" dc:"1 wait 2 success -1 fail"` // 1 wait 2 success -1 fail
	FinishAt     string `protobuf:"bytes,4,opt,name=finishAt,proto3" json:"finishAt,omitempty"`
	Detail       string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	StatusRemark string `protobuf:"bytes,6,opt,name=statusRemark,proto3" json:"statusRemark,omitempty"`
	Amount       string `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	SysRemark    string `protobuf:"bytes,8,opt,name=sysRemark,proto3" json:"sysRemark,omitempty"`
	Address      string `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Fee          string `protobuf:"bytes,10,opt,name=fee,proto3" json:"fee,omitempty"`
	Net          string `protobuf:"bytes,11,opt,name=net,proto3" json:"net,omitempty"`
	Currency     string `protobuf:"bytes,12,opt,name=currency,proto3" json:"currency,omitempty"`
	Protocol     string `protobuf:"bytes,13,opt,name=protocol,proto3" json:"protocol,omitempty"`
	CreatedAt    string `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Account      string `protobuf:"bytes,15,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *PublicWithdrawItem) Reset() {
	*x = PublicWithdrawItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicWithdrawItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicWithdrawItem) ProtoMessage() {}

func (x *PublicWithdrawItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicWithdrawItem.ProtoReflect.Descriptor instead.
func (*PublicWithdrawItem) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{21}
}

func (x *PublicWithdrawItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PublicWithdrawItem) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PublicWithdrawItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PublicWithdrawItem) GetFinishAt() string {
	if x != nil {
		return x.FinishAt
	}
	return ""
}

func (x *PublicWithdrawItem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *PublicWithdrawItem) GetStatusRemark() string {
	if x != nil {
		return x.StatusRemark
	}
	return ""
}

func (x *PublicWithdrawItem) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PublicWithdrawItem) GetSysRemark() string {
	if x != nil {
		return x.SysRemark
	}
	return ""
}

func (x *PublicWithdrawItem) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PublicWithdrawItem) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *PublicWithdrawItem) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *PublicWithdrawItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PublicWithdrawItem) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PublicWithdrawItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PublicWithdrawItem) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type ListPublicWithdrawRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*PublicWithdrawItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListPublicWithdrawRes) Reset() {
	*x = ListPublicWithdrawRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_withdraw_withdraw_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPublicWithdrawRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicWithdrawRes) ProtoMessage() {}

func (x *ListPublicWithdrawRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_withdraw_withdraw_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicWithdrawRes.ProtoReflect.Descriptor instead.
func (*ListPublicWithdrawRes) Descriptor() ([]byte, []int) {
	return file_user_withdraw_withdraw_proto_rawDescGZIP(), []int{22}
}

func (x *ListPublicWithdrawRes) GetList() []*PublicWithdrawItem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_user_withdraw_withdraw_proto protoreflect.FileDescriptor

var file_user_withdraw_withdraw_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2f,
	0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x22, 0x24, 0x0a, 0x10, 0x50, 0x61, 0x79, 0x50,
	0x61, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x2a,
	0x0a, 0x10, 0x50, 0x61, 0x79, 0x50, 0x61, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x35, 0x0a, 0x0d, 0x53, 0x65,
	0x74, 0x50, 0x61, 0x79, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x73,
	0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x50, 0x61, 0x79, 0x50, 0x61, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x16, 0x42, 0x69, 0x6e, 0x64, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x61, 0x6e, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62,
	0x61, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x42,
	0x69, 0x6e, 0x64, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x22, 0x53, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x50, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x50, 0x61, 0x73, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xb7, 0x01, 0x0a, 0x13, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x65,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x22, 0x61, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x31, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x3d, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x61, 0x6e, 0x67, 0x22, 0x48, 0x0a, 0x10, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x42,
	0x69, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xc0, 0x02,
	0x0a, 0x0a, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f,
	0x67, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0c, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x12, 0x2e, 0x0a, 0x04, 0x62, 0x69, 0x6e, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x42, 0x69, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x62, 0x69, 0x6e, 0x64,
	0x22, 0x55, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x73, 0x12, 0x28, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x77, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xa3, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a,
	0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x77, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x13, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52,
	0x65, 0x73, 0x22, 0x4b, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22,
	0xf4, 0x02, 0x0a, 0x0c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x41, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x41, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x52, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x79, 0x73, 0x52, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x66, 0x65, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x65, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x53, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x52, 0x65, 0x71, 0x22, 0x94, 0x03, 0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x57,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x79, 0x73, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65, 0x74,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x49, 0x0a, 0x15, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0xea, 0x05, 0x0a, 0x0f, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0d, 0x50, 0x61,
	0x79, 0x50, 0x61, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x2e, 0x77, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x50, 0x61, 0x79, 0x50, 0x61, 0x73, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x2e, 0x50, 0x61, 0x79, 0x50, 0x61, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x50, 0x61, 0x79, 0x50, 0x61, 0x73,
	0x73, 0x12, 0x17, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x53, 0x65, 0x74,
	0x50, 0x61, 0x79, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x77, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x61, 0x79, 0x50, 0x61, 0x73, 0x73,
	0x52, 0x65, 0x73, 0x12, 0x59, 0x0a, 0x13, 0x42, 0x69, 0x6e, 0x64, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x77, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x77,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x56,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e,
	0x44, 0x65, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x2e, 0x44, 0x65, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x59, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x2e,
	0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x20, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x12, 0x56, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1f, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x12, 0x4a, 0x0a, 0x0e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x12, 0x1b, 0x2e, 0x77, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x12, 0x19, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x12, 0x56, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x12, 0x1f, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52,
	0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x52, 0x65, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_withdraw_withdraw_proto_rawDescOnce sync.Once
	file_user_withdraw_withdraw_proto_rawDescData = file_user_withdraw_withdraw_proto_rawDesc
)

func file_user_withdraw_withdraw_proto_rawDescGZIP() []byte {
	file_user_withdraw_withdraw_proto_rawDescOnce.Do(func() {
		file_user_withdraw_withdraw_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_withdraw_withdraw_proto_rawDescData)
	})
	return file_user_withdraw_withdraw_proto_rawDescData
}

var file_user_withdraw_withdraw_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_user_withdraw_withdraw_proto_goTypes = []interface{}{
	(*PayPassStatusReq)(nil),       // 0: withdraw.PayPassStatusReq
	(*PayPassStatusRes)(nil),       // 1: withdraw.PayPassStatusRes
	(*SetPayPassReq)(nil),          // 2: withdraw.SetPayPassReq
	(*SetPayPassRes)(nil),          // 3: withdraw.SetPayPassRes
	(*BindWithdrawAccountReq)(nil), // 4: withdraw.BindWithdrawAccountReq
	(*BindWithdrawAccountRes)(nil), // 5: withdraw.BindWithdrawAccountRes
	(*DelWithdrawAccountReq)(nil),  // 6: withdraw.DelWithdrawAccountReq
	(*DelWithdrawAccountRes)(nil),  // 7: withdraw.DelWithdrawAccountRes
	(*ListWithdrawAccountReq)(nil), // 8: withdraw.ListWithdrawAccountReq
	(*WithdrawAccountItem)(nil),    // 9: withdraw.WithdrawAccountItem
	(*ListWithdrawAccountRes)(nil), // 10: withdraw.ListWithdrawAccountRes
	(*ListWithdrawMethodReq)(nil),  // 11: withdraw.ListWithdrawMethodReq
	(*WithdrawBindInfo)(nil),       // 12: withdraw.WithdrawBindInfo
	(*AmountItem)(nil),             // 13: withdraw.AmountItem
	(*ListWithdrawMethodRes)(nil),  // 14: withdraw.ListWithdrawMethodRes
	(*CreateWithdrawReq)(nil),      // 15: withdraw.CreateWithdrawReq
	(*CreateWithdrawRes)(nil),      // 16: withdraw.CreateWithdrawRes
	(*ListWithdrawReq)(nil),        // 17: withdraw.ListWithdrawReq
	(*WithdrawItem)(nil),           // 18: withdraw.WithdrawItem
	(*ListWithdrawRes)(nil),        // 19: withdraw.ListWithdrawRes
	(*ListPublicWithdrawReq)(nil),  // 20: withdraw.ListPublicWithdrawReq
	(*PublicWithdrawItem)(nil),     // 21: withdraw.PublicWithdrawItem
	(*ListPublicWithdrawRes)(nil),  // 22: withdraw.ListPublicWithdrawRes
}
var file_user_withdraw_withdraw_proto_depIdxs = []int32{
	9,  // 0: withdraw.ListWithdrawAccountRes.list:type_name -> withdraw.WithdrawAccountItem
	12, // 1: withdraw.AmountItem.bind:type_name -> withdraw.WithdrawBindInfo
	13, // 2: withdraw.ListWithdrawMethodRes.list:type_name -> withdraw.AmountItem
	18, // 3: withdraw.ListWithdrawRes.list:type_name -> withdraw.WithdrawItem
	21, // 4: withdraw.ListPublicWithdrawRes.list:type_name -> withdraw.PublicWithdrawItem
	0,  // 5: withdraw.WithdrawService.PayPassStatus:input_type -> withdraw.PayPassStatusReq
	2,  // 6: withdraw.WithdrawService.SetPayPass:input_type -> withdraw.SetPayPassReq
	4,  // 7: withdraw.WithdrawService.BindWithdrawAccount:input_type -> withdraw.BindWithdrawAccountReq
	6,  // 8: withdraw.WithdrawService.DelWithdrawAccount:input_type -> withdraw.DelWithdrawAccountReq
	8,  // 9: withdraw.WithdrawService.ListWithdrawAccount:input_type -> withdraw.ListWithdrawAccountReq
	11, // 10: withdraw.WithdrawService.ListWithdrawMethod:input_type -> withdraw.ListWithdrawMethodReq
	15, // 11: withdraw.WithdrawService.CreateWithdraw:input_type -> withdraw.CreateWithdrawReq
	17, // 12: withdraw.WithdrawService.ListWithdraw:input_type -> withdraw.ListWithdrawReq
	20, // 13: withdraw.WithdrawService.ListPublicWithdraw:input_type -> withdraw.ListPublicWithdrawReq
	1,  // 14: withdraw.WithdrawService.PayPassStatus:output_type -> withdraw.PayPassStatusRes
	3,  // 15: withdraw.WithdrawService.SetPayPass:output_type -> withdraw.SetPayPassRes
	5,  // 16: withdraw.WithdrawService.BindWithdrawAccount:output_type -> withdraw.BindWithdrawAccountRes
	7,  // 17: withdraw.WithdrawService.DelWithdrawAccount:output_type -> withdraw.DelWithdrawAccountRes
	10, // 18: withdraw.WithdrawService.ListWithdrawAccount:output_type -> withdraw.ListWithdrawAccountRes
	14, // 19: withdraw.WithdrawService.ListWithdrawMethod:output_type -> withdraw.ListWithdrawMethodRes
	16, // 20: withdraw.WithdrawService.CreateWithdraw:output_type -> withdraw.CreateWithdrawRes
	19, // 21: withdraw.WithdrawService.ListWithdraw:output_type -> withdraw.ListWithdrawRes
	22, // 22: withdraw.WithdrawService.ListPublicWithdraw:output_type -> withdraw.ListPublicWithdrawRes
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_user_withdraw_withdraw_proto_init() }
func file_user_withdraw_withdraw_proto_init() {
	if File_user_withdraw_withdraw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_withdraw_withdraw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayPassStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayPassStatusRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPayPassReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPayPassRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindWithdrawAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindWithdrawAccountRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelWithdrawAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelWithdrawAccountRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWithdrawAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawAccountItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWithdrawAccountRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWithdrawMethodReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawBindInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AmountItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWithdrawMethodRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWithdrawReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWithdrawRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWithdrawReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWithdrawRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPublicWithdrawReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicWithdrawItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_withdraw_withdraw_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPublicWithdrawRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_withdraw_withdraw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_withdraw_withdraw_proto_goTypes,
		DependencyIndexes: file_user_withdraw_withdraw_proto_depIdxs,
		MessageInfos:      file_user_withdraw_withdraw_proto_msgTypes,
	}.Build()
	File_user_withdraw_withdraw_proto = out.File
	file_user_withdraw_withdraw_proto_rawDesc = nil
	file_user_withdraw_withdraw_proto_goTypes = nil
	file_user_withdraw_withdraw_proto_depIdxs = nil
}
