// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: user/withdraw/withdraw.proto

package withdraw

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WithdrawService_PayPassStatus_FullMethodName       = "/withdraw.WithdrawService/PayPassStatus"
	WithdrawService_SetPayPass_FullMethodName          = "/withdraw.WithdrawService/SetPayPass"
	WithdrawService_BindWithdrawAccount_FullMethodName = "/withdraw.WithdrawService/BindWithdrawAccount"
	WithdrawService_DelWithdrawAccount_FullMethodName  = "/withdraw.WithdrawService/DelWithdrawAccount"
	WithdrawService_ListWithdrawAccount_FullMethodName = "/withdraw.WithdrawService/ListWithdrawAccount"
	WithdrawService_ListWithdrawMethod_FullMethodName  = "/withdraw.WithdrawService/ListWithdrawMethod"
	WithdrawService_CreateWithdraw_FullMethodName      = "/withdraw.WithdrawService/CreateWithdraw"
	WithdrawService_ListWithdraw_FullMethodName        = "/withdraw.WithdrawService/ListWithdraw"
)

// WithdrawServiceClient is the client API for WithdrawService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WithdrawServiceClient interface {
	// pay pass status
	PayPassStatus(ctx context.Context, in *PayPassStatusReq, opts ...grpc.CallOption) (*PayPassStatusRes, error)
	// set pay password
	SetPayPass(ctx context.Context, in *SetPayPassReq, opts ...grpc.CallOption) (*SetPayPassRes, error)
	// bind withdraw account
	BindWithdrawAccount(ctx context.Context, in *BindWithdrawAccountReq, opts ...grpc.CallOption) (*BindWithdrawAccountRes, error)
	// del withdraw account
	DelWithdrawAccount(ctx context.Context, in *DelWithdrawAccountReq, opts ...grpc.CallOption) (*DelWithdrawAccountRes, error)
	// list withdraw account
	ListWithdrawAccount(ctx context.Context, in *ListWithdrawAccountReq, opts ...grpc.CallOption) (*ListWithdrawAccountRes, error)
	// list withdraw method
	ListWithdrawMethod(ctx context.Context, in *ListWithdrawMethodReq, opts ...grpc.CallOption) (*ListWithdrawMethodRes, error)
	// create withdraw
	CreateWithdraw(ctx context.Context, in *CreateWithdrawReq, opts ...grpc.CallOption) (*CreateWithdrawRes, error)
	// list withdraw
	ListWithdraw(ctx context.Context, in *ListWithdrawReq, opts ...grpc.CallOption) (*ListWithdrawRes, error)
}

type withdrawServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWithdrawServiceClient(cc grpc.ClientConnInterface) WithdrawServiceClient {
	return &withdrawServiceClient{cc}
}

func (c *withdrawServiceClient) PayPassStatus(ctx context.Context, in *PayPassStatusReq, opts ...grpc.CallOption) (*PayPassStatusRes, error) {
	out := new(PayPassStatusRes)
	err := c.cc.Invoke(ctx, WithdrawService_PayPassStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawServiceClient) SetPayPass(ctx context.Context, in *SetPayPassReq, opts ...grpc.CallOption) (*SetPayPassRes, error) {
	out := new(SetPayPassRes)
	err := c.cc.Invoke(ctx, WithdrawService_SetPayPass_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawServiceClient) BindWithdrawAccount(ctx context.Context, in *BindWithdrawAccountReq, opts ...grpc.CallOption) (*BindWithdrawAccountRes, error) {
	out := new(BindWithdrawAccountRes)
	err := c.cc.Invoke(ctx, WithdrawService_BindWithdrawAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawServiceClient) DelWithdrawAccount(ctx context.Context, in *DelWithdrawAccountReq, opts ...grpc.CallOption) (*DelWithdrawAccountRes, error) {
	out := new(DelWithdrawAccountRes)
	err := c.cc.Invoke(ctx, WithdrawService_DelWithdrawAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawServiceClient) ListWithdrawAccount(ctx context.Context, in *ListWithdrawAccountReq, opts ...grpc.CallOption) (*ListWithdrawAccountRes, error) {
	out := new(ListWithdrawAccountRes)
	err := c.cc.Invoke(ctx, WithdrawService_ListWithdrawAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawServiceClient) ListWithdrawMethod(ctx context.Context, in *ListWithdrawMethodReq, opts ...grpc.CallOption) (*ListWithdrawMethodRes, error) {
	out := new(ListWithdrawMethodRes)
	err := c.cc.Invoke(ctx, WithdrawService_ListWithdrawMethod_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawServiceClient) CreateWithdraw(ctx context.Context, in *CreateWithdrawReq, opts ...grpc.CallOption) (*CreateWithdrawRes, error) {
	out := new(CreateWithdrawRes)
	err := c.cc.Invoke(ctx, WithdrawService_CreateWithdraw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawServiceClient) ListWithdraw(ctx context.Context, in *ListWithdrawReq, opts ...grpc.CallOption) (*ListWithdrawRes, error) {
	out := new(ListWithdrawRes)
	err := c.cc.Invoke(ctx, WithdrawService_ListWithdraw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WithdrawServiceServer is the server API for WithdrawService service.
// All implementations must embed UnimplementedWithdrawServiceServer
// for forward compatibility
type WithdrawServiceServer interface {
	// pay pass status
	PayPassStatus(context.Context, *PayPassStatusReq) (*PayPassStatusRes, error)
	// set pay password
	SetPayPass(context.Context, *SetPayPassReq) (*SetPayPassRes, error)
	// bind withdraw account
	BindWithdrawAccount(context.Context, *BindWithdrawAccountReq) (*BindWithdrawAccountRes, error)
	// del withdraw account
	DelWithdrawAccount(context.Context, *DelWithdrawAccountReq) (*DelWithdrawAccountRes, error)
	// list withdraw account
	ListWithdrawAccount(context.Context, *ListWithdrawAccountReq) (*ListWithdrawAccountRes, error)
	// list withdraw method
	ListWithdrawMethod(context.Context, *ListWithdrawMethodReq) (*ListWithdrawMethodRes, error)
	// create withdraw
	CreateWithdraw(context.Context, *CreateWithdrawReq) (*CreateWithdrawRes, error)
	// list withdraw
	ListWithdraw(context.Context, *ListWithdrawReq) (*ListWithdrawRes, error)
	mustEmbedUnimplementedWithdrawServiceServer()
}

// UnimplementedWithdrawServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWithdrawServiceServer struct {
}

func (UnimplementedWithdrawServiceServer) PayPassStatus(context.Context, *PayPassStatusReq) (*PayPassStatusRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayPassStatus not implemented")
}
func (UnimplementedWithdrawServiceServer) SetPayPass(context.Context, *SetPayPassReq) (*SetPayPassRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPayPass not implemented")
}
func (UnimplementedWithdrawServiceServer) BindWithdrawAccount(context.Context, *BindWithdrawAccountReq) (*BindWithdrawAccountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindWithdrawAccount not implemented")
}
func (UnimplementedWithdrawServiceServer) DelWithdrawAccount(context.Context, *DelWithdrawAccountReq) (*DelWithdrawAccountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelWithdrawAccount not implemented")
}
func (UnimplementedWithdrawServiceServer) ListWithdrawAccount(context.Context, *ListWithdrawAccountReq) (*ListWithdrawAccountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWithdrawAccount not implemented")
}
func (UnimplementedWithdrawServiceServer) ListWithdrawMethod(context.Context, *ListWithdrawMethodReq) (*ListWithdrawMethodRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWithdrawMethod not implemented")
}
func (UnimplementedWithdrawServiceServer) CreateWithdraw(context.Context, *CreateWithdrawReq) (*CreateWithdrawRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWithdraw not implemented")
}
func (UnimplementedWithdrawServiceServer) ListWithdraw(context.Context, *ListWithdrawReq) (*ListWithdrawRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWithdraw not implemented")
}
func (UnimplementedWithdrawServiceServer) mustEmbedUnimplementedWithdrawServiceServer() {}

// UnsafeWithdrawServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WithdrawServiceServer will
// result in compilation errors.
type UnsafeWithdrawServiceServer interface {
	mustEmbedUnimplementedWithdrawServiceServer()
}

func RegisterWithdrawServiceServer(s grpc.ServiceRegistrar, srv WithdrawServiceServer) {
	s.RegisterService(&WithdrawService_ServiceDesc, srv)
}

func _WithdrawService_PayPassStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayPassStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).PayPassStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawService_PayPassStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).PayPassStatus(ctx, req.(*PayPassStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawService_SetPayPass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPayPassReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).SetPayPass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawService_SetPayPass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).SetPayPass(ctx, req.(*SetPayPassReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawService_BindWithdrawAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindWithdrawAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).BindWithdrawAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawService_BindWithdrawAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).BindWithdrawAccount(ctx, req.(*BindWithdrawAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawService_DelWithdrawAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelWithdrawAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).DelWithdrawAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawService_DelWithdrawAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).DelWithdrawAccount(ctx, req.(*DelWithdrawAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawService_ListWithdrawAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWithdrawAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).ListWithdrawAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawService_ListWithdrawAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).ListWithdrawAccount(ctx, req.(*ListWithdrawAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawService_ListWithdrawMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWithdrawMethodReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).ListWithdrawMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawService_ListWithdrawMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).ListWithdrawMethod(ctx, req.(*ListWithdrawMethodReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawService_CreateWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWithdrawReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).CreateWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawService_CreateWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).CreateWithdraw(ctx, req.(*CreateWithdrawReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawService_ListWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWithdrawReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).ListWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawService_ListWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).ListWithdraw(ctx, req.(*ListWithdrawReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WithdrawService_ServiceDesc is the grpc.ServiceDesc for WithdrawService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WithdrawService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "withdraw.WithdrawService",
	HandlerType: (*WithdrawServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayPassStatus",
			Handler:    _WithdrawService_PayPassStatus_Handler,
		},
		{
			MethodName: "SetPayPass",
			Handler:    _WithdrawService_SetPayPass_Handler,
		},
		{
			MethodName: "BindWithdrawAccount",
			Handler:    _WithdrawService_BindWithdrawAccount_Handler,
		},
		{
			MethodName: "DelWithdrawAccount",
			Handler:    _WithdrawService_DelWithdrawAccount_Handler,
		},
		{
			MethodName: "ListWithdrawAccount",
			Handler:    _WithdrawService_ListWithdrawAccount_Handler,
		},
		{
			MethodName: "ListWithdrawMethod",
			Handler:    _WithdrawService_ListWithdrawMethod_Handler,
		},
		{
			MethodName: "CreateWithdraw",
			Handler:    _WithdrawService_CreateWithdraw_Handler,
		},
		{
			MethodName: "ListWithdraw",
			Handler:    _WithdrawService_ListWithdraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/withdraw/withdraw.proto",
}
