// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: lottery/lottery/lottery.proto

package slot

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameCode int32   `protobuf:"varint,1,opt,name=gameCode,proto3" json:"gameCode,omitempty"`
	Amount   float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Uid      int64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *SpinReq) Reset() {
	*x = SpinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slot_slot_slot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinReq) ProtoMessage() {}

func (x *SpinReq) ProtoReflect() protoreflect.Message {
	mi := &file_slot_slot_slot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinReq.ProtoReflect.Descriptor instead.
func (*SpinReq) Descriptor() ([]byte, []int) {
	return file_slot_slot_slot_proto_rawDescGZIP(), []int{0}
}

func (x *SpinReq) GetGameCode() int32 {
	if x != nil {
		return x.GameCode
	}
	return 0
}

func (x *SpinReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SpinReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type SpinRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo    int64   `protobuf:"varint,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	OpenResult []int32 `protobuf:"varint,2,rep,packed,name=openResult,proto3" json:"openResult,omitempty"`
}

func (x *SpinRes) Reset() {
	*x = SpinRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slot_slot_slot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpinRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinRes) ProtoMessage() {}

func (x *SpinRes) ProtoReflect() protoreflect.Message {
	mi := &file_slot_slot_slot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinRes.ProtoReflect.Descriptor instead.
func (*SpinRes) Descriptor() ([]byte, []int) {
	return file_slot_slot_slot_proto_rawDescGZIP(), []int{1}
}

func (x *SpinRes) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

func (x *SpinRes) GetOpenResult() []int32 {
	if x != nil {
		return x.OpenResult
	}
	return nil
}

type CheckWonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	OrderNo int64 `protobuf:"varint,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
}

func (x *CheckWonReq) Reset() {
	*x = CheckWonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slot_slot_slot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckWonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWonReq) ProtoMessage() {}

func (x *CheckWonReq) ProtoReflect() protoreflect.Message {
	mi := &file_slot_slot_slot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWonReq.ProtoReflect.Descriptor instead.
func (*CheckWonReq) Descriptor() ([]byte, []int) {
	return file_slot_slot_slot_proto_rawDescGZIP(), []int{2}
}

func (x *CheckWonReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CheckWonReq) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

type CheckWonRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Profit float64 `protobuf:"fixed64,2,opt,name=profit,proto3" json:"profit,omitempty"`
}

func (x *CheckWonRes) Reset() {
	*x = CheckWonRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slot_slot_slot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckWonRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWonRes) ProtoMessage() {}

func (x *CheckWonRes) ProtoReflect() protoreflect.Message {
	mi := &file_slot_slot_slot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWonRes.ProtoReflect.Descriptor instead.
func (*CheckWonRes) Descriptor() ([]byte, []int) {
	return file_slot_slot_slot_proto_rawDescGZIP(), []int{3}
}

func (x *CheckWonRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CheckWonRes) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

var File_slot_slot_slot_proto protoreflect.FileDescriptor

var file_slot_slot_slot_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x6c, 0x6f, 0x74, 0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x2f, 0x73, 0x6c, 0x6f, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x4f, 0x0a, 0x07,
	0x53, 0x70, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x43, 0x0a,
	0x07, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x39, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x57, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x22, 0x3d, 0x0a,
	0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x57, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x32, 0x65, 0x0a, 0x0b,
	0x53, 0x6c, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x53,
	0x70, 0x69, 0x6e, 0x12, 0x0d, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x53, 0x70, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x12, 0x30, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x57, 0x6f, 0x6e, 0x12, 0x11, 0x2e,
	0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x57, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x57, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x73, 0x6c, 0x6f, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_slot_slot_slot_proto_rawDescOnce sync.Once
	file_slot_slot_slot_proto_rawDescData = file_slot_slot_slot_proto_rawDesc
)

func file_slot_slot_slot_proto_rawDescGZIP() []byte {
	file_slot_slot_slot_proto_rawDescOnce.Do(func() {
		file_slot_slot_slot_proto_rawDescData = protoimpl.X.CompressGZIP(file_slot_slot_slot_proto_rawDescData)
	})
	return file_slot_slot_slot_proto_rawDescData
}

var file_slot_slot_slot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_slot_slot_slot_proto_goTypes = []interface{}{
	(*SpinReq)(nil),     // 0: lottery.SpinReq
	(*SpinRes)(nil),     // 1: lottery.SpinRes
	(*CheckWonReq)(nil), // 2: lottery.CheckWonReq
	(*CheckWonRes)(nil), // 3: lottery.CheckWonRes
}
var file_slot_slot_slot_proto_depIdxs = []int32{
	0, // 0: lottery.SlotService.Spin:input_type -> lottery.SpinReq
	2, // 1: lottery.SlotService.CheckWon:input_type -> lottery.CheckWonReq
	1, // 2: lottery.SlotService.Spin:output_type -> lottery.SpinRes
	3, // 3: lottery.SlotService.CheckWon:output_type -> lottery.CheckWonRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_slot_slot_slot_proto_init() }
func file_slot_slot_slot_proto_init() {
	if File_slot_slot_slot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_slot_slot_slot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_slot_slot_slot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpinRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_slot_slot_slot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckWonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_slot_slot_slot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckWonRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_slot_slot_slot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slot_slot_slot_proto_goTypes,
		DependencyIndexes: file_slot_slot_slot_proto_depIdxs,
		MessageInfos:      file_slot_slot_slot_proto_msgTypes,
	}.Build()
	File_slot_slot_slot_proto = out.File
	file_slot_slot_slot_proto_rawDesc = nil
	file_slot_slot_slot_proto_goTypes = nil
	file_slot_slot_slot_proto_depIdxs = nil
}
