app: "gateway"
server:
  address: ":5001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  jwtExpireDuration: "7D" # 7 days
  rootFilePath: "/resource/public/upload/"  # 文件上传路径
  clientMaxBodySize: "200MB"

logger:
  level: "debug"
  stdout: true
database:
  logger:
    level: "debug"
    stdout: true
  default:
    link: "mysql:root:LE2RrzrMxx6Z4sbc@tcp(192.168.0.160:3306)/soccer?loc=Local&parseTime=true"
    debug: true


gfToken:
  name: "star_net_user"
  cacheMode: 2 # 1 gcache  2 redis 3 file
  cacheKey: "start_net_user_token:"
  encryptKey: "koi29a83idakguqjq29asd9asd8a7jhq"
  authFailMsg: "Login timed out, please log in again"
  multiLogin: true
  globalMiddleware: true
redis:
  default:
    address: "192.168.0.160:63790"
    db: 1
    pass: "PqcG15w6#AX$ey0a+BYcCFIpUxLYoukAqhfnfGbnkMtYE"
grpc:
  name:             "gateway"  # 服务名称
  address:          ":5002" # 自定义服务监听地址
  logPath:          "./log" # 日志存储目录路径
  logStdout:        true    # 日志是否输出到终端
  errorLogEnabled:  true    # 是否开启错误日志记录
  accessLogEnabled: true    # 是否开启访问日志记录
  errorStack:       true    # 当产生错误时，是否记录错误堆栈
etcd:
  address: ["8.219.177.71:2379"]
