## upload file
POST {{url}}/api/sys/uploadFile?token=6m2iny016cmcwkns296rn4o100pudkfo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Lark20201204183701.png"
Content-Type: image/png

< /Users/ciel/Downloads/idea.jpeg

