// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game/db/dao/internal"
)

// internalAActivityTypeDao is internal type for wrapping internal DAO implements.
type internalAActivityTypeDao = *internal.AActivityTypeDao

// aActivityTypeDao is the data access object for table a_activity_type.
// You can define custom methods on it to extend its functionality as you wish.
type aActivityTypeDao struct {
	internalAActivityTypeDao
}

var (
	// AActivityType is globally public accessible object for table a_activity_type operations.
	AActivityType = aActivityTypeDao{
		internal.NewAActivityTypeDao(),
	}
)

// Fill with you ideas below.
