// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game/db/dao/internal"
)

// internalAActivityDao is internal type for wrapping internal DAO implements.
type internalAActivityDao = *internal.AActivityDao

// aActivityDao is the data access object for table a_activity.
// You can define custom methods on it to extend its functionality as you wish.
type aActivityDao struct {
	internalAActivityDao
}

var (
	// AActivity is globally public accessible object for table a_activity operations.
	AActivity = aActivityDao{
		internal.NewAActivityDao(),
	}
)

// Fill with you ideas below.
