// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game/db/dao/internal"
)

// internalEEnWordDao is internal type for wrapping internal DAO implements.
type internalEEnWordDao = *internal.EEnWordDao

// eEnWordDao is the data access object for table e_en_word.
// You can define custom methods on it to extend its functionality as you wish.
type eEnWordDao struct {
	internalEEnWordDao
}

var (
	// EEnWord is globally public accessible object for table e_en_word operations.
	EEnWord = eEnWordDao{
		internal.NewEEnWordDao(),
	}
)

// Fill with you ideas below.
