// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game/db/dao/internal"
)

// internalGGameCategoryDao is internal type for wrapping internal DAO implements.
type internalGGameCategoryDao = *internal.GGameCategoryDao

// gGameCategoryDao is the data access object for table g_game_category.
// You can define custom methods on it to extend its functionality as you wish.
type gGameCategoryDao struct {
	internalGGameCategoryDao
}

var (
	// GGameCategory is globally public accessible object for table g_game_category operations.
	GGameCategory = gGameCategoryDao{
		internal.NewGGameCategoryDao(),
	}
)

// Fill with you ideas below.
