// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game/db/dao/internal"
)

// internalGGameTypeDao is internal type for wrapping internal DAO implements.
type internalGGameTypeDao = *internal.GGameTypeDao

// gGameTypeDao is the data access object for table g_game_type.
// You can define custom methods on it to extend its functionality as you wish.
type gGameTypeDao struct {
	internalGGameTypeDao
}

var (
	// GGameType is globally public accessible object for table g_game_type operations.
	GGameType = gGameTypeDao{
		internal.NewGGameTypeDao(),
	}
)

// Fill with you ideas below.
