// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game/db/dao/internal"
)

// internalGPlayDao is internal type for wrapping internal DAO implements.
type internalGPlayDao = *internal.GPlayDao

// gPlayDao is the data access object for table g_play.
// You can define custom methods on it to extend its functionality as you wish.
type gPlayDao struct {
	internalGPlayDao
}

var (
	// GPlay is globally public accessible object for table g_play operations.
	GPlay = gPlayDao{
		internal.NewGPlayDao(),
	}
)

// Fill with you ideas below.
