// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game/db/dao/internal"
)

// internalGameCategoryDao is internal implement for wrapping internal DAO implements.
type internalGameCategoryDao = *internal.GameCategoryDao

// gameCategoryDao is the data access object for table g_game_category.
// You can define custom methods on it to extend its functionality as you wish.
type gameCategoryDao struct {
	internalGameCategoryDao
}

var (
	// GameCategory is globally public accessible object for table g_game_category operations.
	GameCategory = gameCategoryDao{
		internal.NewGameCategoryDao(),
	}
)

// Fill with you ideas below.
