// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game/db/dao/internal"
)

// internalSlotOrderDao is internal implement for wrapping internal DAO implements.
type internalSlotOrderDao = *internal.SlotOrderDao

// slotOrderDao is the data access object for table g_slot_order.
// You can define custom methods on it to extend its functionality as you wish.
type slotOrderDao struct {
	internalSlotOrderDao
}

var (
	// SlotOrder is globally public accessible object for table g_slot_order operations.
	SlotOrder = slotOrderDao{
		internal.NewSlotOrderDao(),
	}
)

// Fill with you ideas below.
