// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game/db/dao/internal"
)

// internalTaskCategoryDao is internal implement for wrapping internal DAO implements.
type internalTaskCategoryDao = *internal.TaskCategoryDao

// taskCategoryDao is the data access object for table a_task_category.
// You can define custom methods on it to extend its functionality as you wish.
type taskCategoryDao struct {
	internalTaskCategoryDao
}

var (
	// TaskCategory is globally public accessible object for table a_task_category operations.
	TaskCategory = taskCategoryDao{
		internal.NewTaskCategoryDao(),
	}
)

// Fill with you ideas below.
