// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game/db/dao/internal"
)

// internalTransactionTypeDao is internal implement for wrapping internal DAO implements.
type internalTransactionTypeDao = *internal.TransactionTypeDao

// transactionTypeDao is the data access object for table w_transaction_type.
// You can define custom methods on it to extend its functionality as you wish.
type transactionTypeDao struct {
	internalTransactionTypeDao
}

var (
	// TransactionType is globally public accessible object for table w_transaction_type operations.
	TransactionType = transactionTypeDao{
		internal.NewTransactionTypeDao(),
	}
)

// Fill with you ideas below.
