// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game/db/dao/internal"
)

// internalWithdrawDao is internal implement for wrapping internal DAO implements.
type internalWithdrawDao = *internal.WithdrawDao

// withdrawDao is the data access object for table w_withdraw.
// You can define custom methods on it to extend its functionality as you wish.
type withdrawDao struct {
	internalWithdrawDao
}

var (
	// Withdraw is globally public accessible object for table w_withdraw operations.
	Withdraw = withdrawDao{
		internal.NewWithdrawDao(),
	}
)

// Fill with you ideas below.
