app: "gateway"
server:
  address: ":5003"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  jwtExpireDuration: "7D" # 7 days
  rootFilePath: "/resource/public/upload/"  # 文件上传路径
  clientMaxBodySize: "200MB"

logger:
  level: "debug"
  stdout: true
database:
  logger:
    level: "debug"
    stdout: true
  default:
    link: "mysql:root:LE2RrzrMxx6Z4sbc@tcp(8.219.177.71:3306)/game?loc=Local&parseTime=true"
    debug: true
redis:
  default:
    address: "8.219.177.71:63790"
    db: 3
    pass: "PqcG15w6#AX$ey0a+BYcCFIpUxLYoukAqhfnfGbnkMtYE"
grpc:
  name: "user_svc"  # 服务名称
  address: ":5001" # 自定义服务监听地址
  logPath: "./log" # 日志存储目录路径
  logStdout: true    # 日志是否输出到终端
  errorLogEnabled: true    # 是否开启错误日志记录
  accessLogEnabled: true    # 是否开启访问日志记录
  errorStack: true    # 当产生错误时，是否记录错误堆栈
etcd:
  address: [ "8.219.177.71:2379" ]
pusher:
  appId: "1696531"
  key: "bb8063bd4d4939b6c4ea"
  secret: "366111b02e0482f92d16"
  cluster: "mt1"